servers:
   -url: ''
openapi: 3.0.3
info:
  description: API Description
  title: Spredmo API
  version: 1.0.0
paths:
  /aoamodel:
    post:
      summary: 'Endpunkt der AOA script startet MIT model'
      responses:
        default:
          description: Default response.
      parameters: []
      requestBody:
        description: User inputs
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: [{"cloud_cover": 50,"start_day": "2021-04-01","end_day": "2021-04-30","resolution": 100,"path_model": "tmp/model.rds","path_aoi": "tmp/aoi.geojson"}]
  /aoatdata:
    post:
      summary: 'Endpunkt der AOA script startet OHNE model MIT trainingsdaten'
      responses:
        default:
          description: Default response.
      parameters: []
      requestBody:
        description: User inputs
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: [{"cloud_cover": 50,"start_day": "2021-04-01","end_day": "2021-04-30","resolution": 100,"path_tdata": "tmp/tdata.geojson","path_aoi": "tmp/aoi.geojson"}]
  /refresh:
    get:
      summary: 'Endpunkt um den tmp Ordner zu leeren'
      responses:
        '200':
          description: tmp has been cleared successfully